// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyGgYL0vUll5irfg_eLNDMDb1NnyCdC8Y',
    appId: '1:287850376558:web:d7314d5046b2dd80bae57f',
    messagingSenderId: '287850376558',
    projectId: 'marketfresh-6a312',
    authDomain: 'marketfresh-6a312.firebaseapp.com',
    storageBucket: 'marketfresh-6a312.firebasestorage.app',
    measurementId: 'G-RJFZCJ0XL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT19M98gESlGP_Efhr35Jru0AuHV73Noc',
    appId: '1:287850376558:android:c790d6a8bd1789fabae57f',
    messagingSenderId: '287850376558',
    projectId: 'marketfresh-6a312',
    storageBucket: 'marketfresh-6a312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfQLez4zkfbJZ9Sn61tINlVa8ISUH5VEI',
    appId: '1:287850376558:ios:6acf6d2b3c20ad79bae57f',
    messagingSenderId: '287850376558',
    projectId: 'marketfresh-6a312',
    storageBucket: 'marketfresh-6a312.firebasestorage.app',
    iosBundleId: 'com.example.marketfresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfQLez4zkfbJZ9Sn61tINlVa8ISUH5VEI',
    appId: '1:287850376558:ios:6acf6d2b3c20ad79bae57f',
    messagingSenderId: '287850376558',
    projectId: 'marketfresh-6a312',
    storageBucket: 'marketfresh-6a312.firebasestorage.app',
    iosBundleId: 'com.example.marketfresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyGgYL0vUll5irfg_eLNDMDb1NnyCdC8Y',
    appId: '1:287850376558:web:d7b6957c76870f0bbae57f',
    messagingSenderId: '287850376558',
    projectId: 'marketfresh-6a312',
    authDomain: 'marketfresh-6a312.firebaseapp.com',
    storageBucket: 'marketfresh-6a312.firebasestorage.app',
    measurementId: 'G-ESWNWYZTSZ',
  );
}
